# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smarthr
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration (Add below existing code)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saahopradeep63@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=bXlTdXBlclNlY3VyZUp3dFNlY3JldEtleUZvclByb2plY3QyMDI2MTIzNDU2
jwt.expiration=86400000

